# Generated by Django 3.1.1 on 2020-09-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('First_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('Patronymic', models.CharField(blank=True, max_length=20, verbose_name='Отчество')),
                ('Description', models.CharField(blank=True, max_length=100, verbose_name='Описание')),
                ('Birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('Number', models.CharField(max_length=13, verbose_name='Номер телефона')),
                ('Email', models.CharField(blank=True, max_length=50, verbose_name='Электронная почта')),
                ('Social_networks', models.CharField(blank=True, max_length=50, verbose_name='Соц.сети')),
            ],
        ),
    ]
