# Generated by Django 3.1.1 on 2020-09-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Patronymic',
            new_name='patronymic',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Birthday',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Social_networks',
        ),
        migrations.AddField(
            model_name='contact',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=50, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='contact',
            name='social_networks',
            field=models.CharField(blank=True, max_length=300, verbose_name='Соц.сети'),
        ),
    ]
